### PR TITLE
METAGEN-94

### PR DESCRIPTION
**Pull request by gunnarmorling**

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@hferentschik: I haven't done the renaming (yet) because it affects quite a lot of places. But if you like, I can rename `MetaEntity` into `MetaType` (or `MetaPersistentType`?) and the two implementations for annotations and XML.

**Comment by gunnarmorling** [comment]
Hmmm, still failing on CI. Need to have another look.

**Comment by gunnarmorling** [comment]
Jenkins, retest this, please.

**Comment by hferentschik** [comment]
> @hferentschik: I haven't done the renaming (yet) because it affects quite a lot of places. But if you like, I can rename MetaEntity into MetaType (or MetaPersistentType?) and the two implementations for annotations and XML.

I think for now we can live w/o a rename. WDYT? Of course we need to get it to work first.

**Comment by gunnarmorling** [comment]
> I think for now we can live w/o a rename. WDYT?

Yes, same here. May be worth digging in the JPA spec what they use as common term for entity, embeddables and mapped superclasses.

> Of course we need to get it to work first.

It seems to be an issue with the CI job config. The same job builds master and PRs (unlike e.g. for Search), and apparently it just built the master branch with the last run. Looking into it as we speak.

**Comment by gunnarmorling** [comment]
Jenkins, retest this, please.

**Comment by gunnarmorling** [comment]
There you go :) Got two jobs now, [hibernate-metamodelgen-PR](http://ci.hibernate.org/view/Pull%20Requests/job/hibernate-metamodelgen-PR/) (passing now) and [hibernate-metamodelgen-master](http://ci.hibernate.org/view/Master/job/hibernate-metamodelgen-master/).

**Comment by hferentschik** [comment]
It is odd, on my ubuntu test setup only _MixedConfigurationTest_ is failing. I only see _ MappedSuperclassWithoutExplicitIdTest_ failing on Jenkins.

**Comment by hferentschik** [comment]
btw, did you change the Jenkins config? Personally I liked it that to have a single job for master and pull request building. It seems though that the build passes now.

**Comment by gunnarmorling** [comment]
> It is odd, on my ubuntu test setup only MixedConfigurationTest is failing. I only see _ MappedSuperclassWithoutExplicitIdTest_ failing on Jenkins.

That's odd indeed. It failed for me on Ubuntu, too. Maybe something else has an influence on the iteration order. Anyways, should be fixed now.

Looking into `MixedConfigurationTest` now.

> btw, did you change the Jenkins config? 

Yes, I did. There are two jobs now, [hibernate-metamodelgen-PR](http://ci.hibernate.org/view/Pull%20Requests/job/hibernate-metamodelgen-PR/) (which passes now with my change) and [hibernate-metamodelgen-master](http://ci.hibernate.org/view/Master/job/hibernate-metamodelgen-master/).

**Comment by hferentschik** [comment]
Actually this change makes the code easier. I guess the only drawback is the ambiguous name of _MetaEntity_.

**Comment by hferentschik** [comment]
> Looking into MixedConfigurationTest now.

Awesome. Might be similar.

> Yes, I did. There are two jobs now, hibernate-metamodelgen-PR (which passes now with my change) and hibernate-metamodelgen-master.

smaken är som baken

**Comment by hferentschik** [comment]
Nice first successful build of master

**Pull request merged**
